#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 04, 2020 05:57:33 PM EST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 438x478
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight bold} -foreground #2432d9 \
        -text {Software Not Installed} 
    vTcl:DefineAlias "$top.lab43" "Header" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab43
    label $top.lab44 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -text {Warning: Youre missing Tesseract. it is a required software to make this tool run. To fix this issue, please follow the instructions below.} \
        -wraplength 294 
    vTcl:DefineAlias "$top.lab44" "info0" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab44
    label $top.lab45 \
        -background #eeeeee -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -text {If you havent already installed this software, please follow the download link.} \
        -wraplength 294 
    vTcl:DefineAlias "$top.lab45" "info1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab45
    label $top.lab47 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #29c1dc \
        -text Or 
    vTcl:DefineAlias "$top.lab47" "tor" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab47
    label $top.lab48 \
        -background #eeeeee -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -text {If you've already installed the software, please lead us to where it is as we cannot find it.} \
        -wraplength 294 
    vTcl:DefineAlias "$top.lab48" "info2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab48
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #48d250 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Download __} 
    vTcl:DefineAlias "$top.but49" "download" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {This will take you to the official download page for __}
    }
    vTcl:copy_lock $top.but49
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #eaecec -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Navigate to __} 
    vTcl:DefineAlias "$top.but50" "navigate" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {If you've already installed the program but still get this error. Show us where the software is installed and well take care of the rest.}
    }
    vTcl:copy_lock $top.but50
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 70 -y 20 -width 294 -relwidth 0 -height 61 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 70 -y 80 -width 294 -relwidth 0 -height 151 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 70 -y 250 -width 294 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 200 -y 330 -width 40 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 70 -y 370 -width 294 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 70 -y 290 -width 297 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 70 -y 420 -width 297 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

