#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Mar 31, 2020 10:57:20 PM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import mainGuiRevamp_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    mainGuiRevamp_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    mainGuiRevamp_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+401+150")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.inputSheet = tk.Button(top)
        self.inputSheet.place(relx=0.033, rely=0.044, height=34, width=157)
        self.inputSheet.configure(activebackground="#ececec")
        self.inputSheet.configure(activeforeground="#000000")
        self.inputSheet.configure(background="#d9d9d9")
        self.inputSheet.configure(disabledforeground="#a3a3a3")
        self.inputSheet.configure(foreground="#000000")
        self.inputSheet.configure(highlightbackground="#d9d9d9")
        self.inputSheet.configure(highlightcolor="black")
        self.inputSheet.configure(pady="0")
        self.inputSheet.configure(text='''Select Signin sheet''')

        self.outputCSV = tk.Button(top)
        self.outputCSV.place(relx=0.033, rely=0.156, height=34, width=157)
        self.outputCSV.configure(activebackground="#ececec")
        self.outputCSV.configure(activeforeground="#000000")
        self.outputCSV.configure(background="#d9d9d9")
        self.outputCSV.configure(disabledforeground="#a3a3a3")
        self.outputCSV.configure(foreground="#000000")
        self.outputCSV.configure(highlightbackground="#d9d9d9")
        self.outputCSV.configure(highlightcolor="black")
        self.outputCSV.configure(pady="0")
        self.outputCSV.configure(text='''Select output csv''')

        self.imagePortrait = tk.Label(top)
        self.imagePortrait.place(relx=0.417, rely=0.022, height=221, width=314)
        self.imagePortrait.configure(activebackground="#f9f9f9")
        self.imagePortrait.configure(activeforeground="black")
        self.imagePortrait.configure(background="#e6e6e6")
        self.imagePortrait.configure(disabledforeground="#a3a3a3")
        self.imagePortrait.configure(foreground="#000000")
        self.imagePortrait.configure(highlightbackground="#d9d9d9")
        self.imagePortrait.configure(highlightcolor="black")
        self.imagePortrait.configure(text='''Label''')

        self.errorLabel = tk.Label(top)
        self.errorLabel.place(relx=0.017, rely=0.356, height=71, width=224)
        self.errorLabel.configure(activebackground="#f9f9f9")
        self.errorLabel.configure(activeforeground="black")
        self.errorLabel.configure(background="#e1e1e1")
        self.errorLabel.configure(disabledforeground="#a3a3a3")
        self.errorLabel.configure(foreground="#ff0000")
        self.errorLabel.configure(highlightbackground="#d9d9d9")
        self.errorLabel.configure(highlightcolor="black")
        self.errorLabel.configure(text='''Uh oh. It looks like we couldnt condifently decide who or what this is. We need you to either confirm our guess or type in the correct value''')

        self.correctionEntry = tk.Entry(top)
        self.correctionEntry.place(relx=0.133, rely=0.689, height=30
                , relwidth=0.557)
        self.correctionEntry.configure(background="white")
        self.correctionEntry.configure(disabledforeground="#a3a3a3")
        self.correctionEntry.configure(font="TkFixedFont")
        self.correctionEntry.configure(foreground="#000000")
        self.correctionEntry.configure(highlightbackground="#d9d9d9")
        self.correctionEntry.configure(highlightcolor="black")
        self.correctionEntry.configure(insertbackground="black")
        self.correctionEntry.configure(selectbackground="#c4c4c4")
        self.correctionEntry.configure(selectforeground="black")

        self.AIGuess = tk.Button(top)
        self.AIGuess.place(relx=0.55, rely=0.556, height=34, width=227)
        self.AIGuess.configure(activebackground="#ececec")
        self.AIGuess.configure(activeforeground="#000000")
        self.AIGuess.configure(background="#d9d9d9")
        self.AIGuess.configure(disabledforeground="#a3a3a3")
        self.AIGuess.configure(foreground="#000000")
        self.AIGuess.configure(highlightbackground="#d9d9d9")
        self.AIGuess.configure(highlightcolor="black")
        self.AIGuess.configure(pady="0")
        self.AIGuess.configure(text='''Button''')

        self.submit = tk.Button(top)
        self.submit.place(relx=0.717, rely=0.689, height=34, width=127)
        self.submit.configure(activebackground="#ececec")
        self.submit.configure(activeforeground="#000000")
        self.submit.configure(background="#d9d9d9")
        self.submit.configure(disabledforeground="#a3a3a3")
        self.submit.configure(foreground="#000000")
        self.submit.configure(highlightbackground="#d9d9d9")
        self.submit.configure(highlightcolor="black")
        self.submit.configure(pady="0")
        self.submit.configure(text='''Submit''')

        self.confidenceDescription = tk.Label(top)
        self.confidenceDescription.place(relx=0.267, rely=0.556, height=31
                , width=164)
        self.confidenceDescription.configure(activebackground="#f9f9f9")
        self.confidenceDescription.configure(activeforeground="black")
        self.confidenceDescription.configure(background="#d9d9d9")
        self.confidenceDescription.configure(disabledforeground="#a3a3a3")
        self.confidenceDescription.configure(foreground="#000000")
        self.confidenceDescription.configure(highlightbackground="#d9d9d9")
        self.confidenceDescription.configure(highlightcolor="black")
        self.confidenceDescription.configure(justify='right')
        self.confidenceDescription.configure(text='''Were not confident, but is it:''')

        self.orLabel = tk.Label(top)
        self.orLabel.place(relx=0.017, rely=0.689, height=31, width=64)
        self.orLabel.configure(activebackground="#f9f9f9")
        self.orLabel.configure(activeforeground="black")
        self.orLabel.configure(background="#d9d9d9")
        self.orLabel.configure(disabledforeground="#a3a3a3")
        self.orLabel.configure(foreground="#000000")
        self.orLabel.configure(highlightbackground="#d9d9d9")
        self.orLabel.configure(highlightcolor="black")
        self.orLabel.configure(text='''Or''')

        self.TranslationProgress = ttk.Progressbar(top)
        self.TranslationProgress.place(relx=0.017, rely=0.911, relwidth=0.95
                , relheight=0.0, height=22)

        self.SheetStatus = tk.Label(top)
        self.SheetStatus.place(relx=0.033, rely=0.844, height=21, width=554)
        self.SheetStatus.configure(activebackground="#f9f9f9")
        self.SheetStatus.configure(activeforeground="black")
        self.SheetStatus.configure(anchor='w')
        self.SheetStatus.configure(background="#d9d9d9")
        self.SheetStatus.configure(disabledforeground="#a3a3a3")
        self.SheetStatus.configure(foreground="#000000")
        self.SheetStatus.configure(highlightbackground="#d9d9d9")
        self.SheetStatus.configure(highlightcolor="black")
        self.SheetStatus.configure(text='''Sheet: x of y''')

        self.start = tk.Button(top)
        self.start.place(relx=0.033, rely=0.256, height=34, width=157)
        self.start.configure(activebackground="#ececec")
        self.start.configure(activeforeground="#000000")
        self.start.configure(background="#17a252")
        self.start.configure(disabledforeground="#a3a3a3")
        self.start.configure(foreground="#ffffff")
        self.start.configure(highlightbackground="#d9d9d9")
        self.start.configure(highlightcolor="black")
        self.start.configure(pady="0")
        self.start.configure(text='''Start''')

        self.version = tk.Label(top)
        self.version.place(relx=0.033, rely=0.8, height=21, width=134)
        self.version.configure(anchor='w')
        self.version.configure(background="#d9d9d9")
        self.version.configure(disabledforeground="#a3a3a3")
        self.version.configure(foreground="#000000")
        self.version.configure(text='''Version''')

if __name__ == '__main__':
    vp_start_gui()





